= Camel Java DSL Maven Plugin

The Camel Java DSL Maven Plugin supports the following goals

 - camel-java-dsl:generate - To generate source code line number mapping files for Java Routes

== camel:generate

To scan source code for Java Routes and generate mapping files, that maps the route EIPs
to their source code line number. This allows Camel to enrich the loaded routes with this
information.

This can be used by tooling such as debuggers.

----
mvn camel-java-dsl:generate
----

You should

[source,xml]
----
<plugin>
  <groupId>org.apache.camel</groupId>
  <artifactId>camel-java-dsl-maven-plugin</artifactId>
  <executions>
    <execution>
      <phase>process-classes</phase>
      <goals>
        <goal>generate</goal>
      </goals>
    </execution>
  </executions>
</plugin>
----

The phase determines when the plugin runs. In the sample above the phase is `process-classes` which runs after
the compilation of the main source code.

=== Options

The maven plugin *generate* goal supports the following options which can be configured from the command line (use `-D` syntax), or defined in the `pom.xml` file in the `<configuration>` tag.

|===
| Parameter | Default Value | Description
| includeTest | false | Whether to include test source code
| includes | | To filter the names of java files to only include files matching any of the given list of patterns (wildcard and regular expression). Multiple values can be separated by comma.
| excludes | | To filter the names of java files to exclude files matching any of the given list of patterns (wildcard and regular expression). Multiple values can be separated by comma.
|===

